package com.ossi.laneforge;

import android.content.Context;
import android.graphics.*;
import android.view.*;
import java.util.*;

public final class GameView extends View implements Runnable {
  static final int W=1080,H=1920, P=0,B=1; Paint p=new Paint(3); Random r=new Random();
  ArrayList<U> us=new ArrayList<>(); ArrayList<T> ts=new ArrayList<>();
  boolean run; long last; int state=0,sel=-1,winner=-1,pc,bc; float pe,be,time,bot;
  int[] hand={0,1,2,3}; int next=4; float sc,ox,oy;
  String[] names={"Vanguard","Ranger","Koloss","Funken","Werfer","Lancier","Frostling","Meteor"};
  int[] cost={3,3,5,2,3,4,4,4};
  public GameView(Context c){super(c);setBackgroundColor(Color.BLACK);}
  public void resumeGame(){if(run)return;run=true;last=System.nanoTime();postOnAnimation(this);} public void pauseGame(){run=false;removeCallbacks(this);} 
  protected void onSizeChanged(int w,int h,int a,int b){sc=Math.min(w/1080f,h/1920f);ox=(w-1080*sc)/2;oy=(h-1920*sc)/2;}
  public void run(){if(!run)return;long n=System.nanoTime();float d=Math.min(.033f,(n-last)/1e9f);last=n;if(state==1)upd(d);invalidate();postOnAnimation(this);} 
  void start(){state=1;winner=-1;sel=-1;pe=be=5;time=180;bot=1;pc=bc=0;us.clear();ts.clear();hand=new int[]{0,1,2,3};next=4;
    ts.add(new T(B,280,330,false));ts.add(new T(B,800,330,false));ts.add(new T(B,540,180,true));
    ts.add(new T(P,280,1300,false));ts.add(new T(P,800,1300,false));ts.add(new T(P,540,1450,true));}
  void upd(float d){time-=d;float rg=time<60?1.25f:.72f;pe=Math.min(10,pe+rg*d);be=Math.min(10,be+rg*d);bot-=d;if(bot<0){ai();bot=.8f+r.nextFloat();}
    for(T t:ts){if(!t.ok)continue;t.cd-=d;U q=null;float bd=9999;for(U u:us)if(u.team!=t.team&&u.hp>0){float z=dist(t.x,t.y,u.x,u.y);if(z<t.range&&z<bd){bd=z;q=u;}}if(q!=null&&t.cd<=0){q.hp-=t.core?90:72;t.cd=t.core?.8f:1f;}}
    for(U u:new ArrayList<>(us)){if(u.hp<=0)continue;u.cd-=d;Object tg=target(u);if(tg==null)continue;float tx=tg instanceof U?((U)tg).x:((T)tg).x,ty=tg instanceof U?((U)tg).y:((T)tg).y,rad=tg instanceof U?((U)tg).rad:55;float z=dist(u.x,u.y,tx,ty);if(z<u.range+rad){if(u.cd<=0){u.cd=u.rate;if(tg instanceof U)((U)tg).hp-=u.dmg;else hit((T)tg,u.dmg,u.team);}}else{float bx=u.lane<540?300:780;if((u.y>820&&ty<820)||(u.y<820&&ty>820)){if(Math.abs(u.y-820)>95){tx=bx;ty=u.y>820?875:765;}}move(u,tx,ty,u.sp*d);}}
    us.removeIf(x->x.hp<=0);if(time<=0){int a=score();finish(a>=0?P:B);}}
  Object target(U u){U q=null;float bd=360;for(U v:us)if(v.team!=u.team&&v.hp>0){float z=dist(u.x,u.y,v.x,v.y);if(z<bd){bd=z;q=v;}}if(q!=null&&!u.build)return q;T best=null;for(T t:ts)if(t.team!=u.team&&t.ok){if(!t.core&&((u.lane<540&&t.x<540)||(u.lane>=540&&t.x>540)))return t;if(best==null||dist(u.x,u.y,t.x,t.y)<dist(u.x,u.y,best.x,best.y))best=t;}return best;}
  void move(U u,float x,float y,float a){float dx=x-u.x,dy=y-u.y,l=(float)Math.sqrt(dx*dx+dy*dy);if(l>1){u.x+=dx/l*Math.min(a,l);u.y+=dy/l*Math.min(a,l);}}
  void hit(T t,float d,int team){if(!t.ok)return;t.hp-=d;if(t.hp<=0){t.ok=false;if(team==P)pc+=t.core?3:1;else bc+=t.core?3:1;if(t.core)finish(team);}}
  int score(){if(pc!=bc)return pc>bc?1:-1;float a=0,b=0;for(T t:ts){if(t.team==P)a+=Math.max(0,t.hp/t.max);else b+=Math.max(0,t.hp/t.max);}return a>=b?1:-1;}
  void finish(int w){if(state!=1)return;winner=w;state=2;}
  void ai(){ArrayList<Integer> ok=new ArrayList<>();for(int i=0;i<8;i++)if(cost[i]<=be)ok.add(i);if(ok.isEmpty())return;int c=ok.get(r.nextInt(ok.size()));float x=r.nextBoolean()?280:800,y=470+r.nextFloat()*150;if(c==7){x=280+r.nextInt(2)*520;y=1200;}deploy(B,c,x,y);be-=cost[c];}
  void deploy(int team,int c,float x,float y){if(c==7){for(U u:us)if(u.team!=team&&dist(x,y,u.x,u.y)<160)u.hp-=300;for(T t:ts)if(t.team!=team&&dist(x,y,t.x,t.y)<200)hit(t,200,team);return;}int n=c==3?3:1;for(int i=0;i<n;i++){U u=new U();u.team=team;u.type=c;u.x=x+(i-1)*35;u.y=y;u.lane=x;switch(c){case 0:u.set(520,82,72,38,.85f,29,false);break;case 1:u.set(270,68,62,245,1.05f,24,false);break;case 2:u.set(1450,128,39,42,1.35f,40,true);break;case 3:u.set(125,44,108,26,.58f,18,false);break;case 4:u.set(315,106,54,215,1.45f,25,false);break;case 5:u.set(670,110,96,42,.95f,31,false);break;case 6:u.set(430,72,57,225,1.2f,27,false);}us.add(u);}}
  protected void onDraw(Canvas c){super.onDraw(c);c.save();c.translate(ox,oy);c.scale(sc,sc);if(state==0)menu(c);else{arena(c);towers(c);units(c);hud(c);if(state==2)over(c);}c.restore();}
  void menu(Canvas c){p.setColor(Color.rgb(18,25,46));c.drawRect(0,0,W,H,p);txt(c,"LANEFORGE",540,650,100,Color.WHITE,true);txt(c,"Offline Karten-Arena gegen Bots",540,730,34,Color.CYAN,false);btn(c,180,980,900,1140,"BOT-KAMPF STARTEN",Color.rgb(45,185,115));txt(c,"8 Karten • 2 Lanes • 6 Türme",540,1300,32,Color.LTGRAY,false);}
  void arena(Canvas c){p.setColor(Color.rgb(55,140,75));c.drawRect(0,120,W,1545,p);p.setColor(Color.rgb(50,155,205));c.drawRect(0,745,W,895,p);p.setColor(Color.rgb(185,135,75));c.drawRect(205,725,395,915,p);c.drawRect(685,725,875,915,p);}
  void towers(Canvas c){for(T t:ts){if(!t.ok)continue;p.setColor(t.team==P?Color.rgb(65,165,225):Color.rgb(220,75,75));float s=t.core?72:58;c.drawRoundRect(t.x-s,t.y-s,t.x+s,t.y+s,18,18,p);txt(c,t.core?"K":"W",t.x,t.y+14,40,Color.WHITE,true);bar(c,t.x-75,t.y-s-28,150,14,t.hp/t.max,t.team==P?Color.CYAN:Color.RED);}}
  void units(Canvas c){for(U u:us){p.setColor(color(u.type));c.drawCircle(u.x,u.y,u.rad,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(6);p.setColor(u.team==P?Color.CYAN:Color.RED);c.drawCircle(u.x,u.y,u.rad+3,p);p.setStyle(Paint.Style.FILL);txt(c,""+(u.type+1),u.x,u.y+10,24,Color.BLACK,true);bar(c,u.x-35,u.y-u.rad-18,70,8,u.hp/u.max,u.team==P?Color.CYAN:Color.RED);}}
  void hud(Canvas c){p.setColor(Color.rgb(22,27,42));c.drawRect(0,0,W,120,p);c.drawRect(0,1545,W,H,p);int s=Math.max(0,(int)Math.ceil(time));txt(c,String.format(Locale.GERMANY,"%d:%02d",s/60,s%60),540,78,48,Color.WHITE,true);txt(c,"BOT "+bc,35,75,30,Color.RED,true,Paint.Align.LEFT);txt(c,"DU "+pc,1045,75,30,Color.CYAN,true,Paint.Align.RIGHT);float gap=18,cw=(W-56-3*gap)/4;for(int i=0;i<4;i++){float l=28+i*(cw+gap);card(c,l,1570,l+cw,1815,hand[i],i==sel,pe>=cost[hand[i]]);}p.setColor(Color.rgb(70,40,90));c.drawRoundRect(70,1845,1010,1900,25,25,p);p.setColor(Color.MAGENTA);c.drawRoundRect(75,1850,75+930*(pe/10),1895,20,20,p);txt(c,String.format(Locale.GERMANY,"ENERGIE %.1f / 10",pe),540,1885,28,Color.WHITE,true);}
  void card(Canvas c,float l,float t,float rr,float b,int ty,boolean s,boolean a){p.setColor(s?Color.YELLOW:Color.DKGRAY);c.drawRoundRect(l,t,rr,b,24,24,p);p.setColor(a?Color.rgb(40,50,75):Color.GRAY);c.drawRoundRect(l+8,t+8,rr-8,b-8,18,18,p);p.setColor(color(ty));c.drawCircle((l+rr)/2,t+82,52,p);txt(c,names[ty],(l+rr)/2,t+170,24,Color.WHITE,true);p.setColor(Color.MAGENTA);c.drawCircle(l+35,t+35,28,p);txt(c,""+cost[ty],l+35,t+45,28,Color.WHITE,true);}
  void over(Canvas c){p.setColor(Color.argb(210,0,0,0));c.drawRect(0,0,W,H,p);txt(c,winner==P?"SIEG":"NIEDERLAGE",540,750,90,winner==P?Color.YELLOW:Color.RED,true);txt(c,"Kronen "+pc+" : "+bc,540,850,40,Color.WHITE,true);btn(c,190,1100,890,1260,"NOCH EIN KAMPF",Color.rgb(45,185,115));btn(c,280,1320,800,1450,"HAUPTMENÜ",Color.rgb(55,115,205));}
  public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=0)return true;float x=(e.getX()-ox)/sc,y=(e.getY()-oy)/sc;if(state==0){if(in(x,y,180,980,900,1140))start();return true;}if(state==2){if(in(x,y,190,1100,890,1260))start();else if(in(x,y,280,1320,800,1450))state=0;return true;}if(y>=1570&&y<=1815){float gap=18,cw=(W-56-3*gap)/4;for(int i=0;i<4;i++){float l=28+i*(cw+gap);if(x>=l&&x<=l+cw){sel=sel==i?-1:i;return true;}}}if(sel>=0&&y>=120&&y<=1545){int c=hand[sel];if(pe<cost[c])return true;if(c!=7&&y<920)return true;deploy(P,c,x,y);pe-=cost[c];hand[sel]=next;next=(next+1)%8;sel=-1;}return true;}
  void txt(Canvas c,String s,float x,float y,float z,int col,boolean b){txt(c,s,x,y,z,col,b,Paint.Align.CENTER);}void txt(Canvas c,String s,float x,float y,float z,int col,boolean b,Paint.Align a){p.setColor(col);p.setTextSize(z);p.setTextAlign(a);p.setTypeface(b?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);c.drawText(s,x,y,p);}void btn(Canvas c,float l,float t,float rr,float b,String s,int col){p.setColor(col);c.drawRoundRect(l,t,rr,b,30,30,p);txt(c,s,(l+rr)/2,(t+b)/2+14,38,Color.WHITE,true);}void bar(Canvas c,float x,float y,float w,float h,float q,int col){p.setColor(Color.DKGRAY);c.drawRect(x,y,x+w,y+h,p);p.setColor(col);c.drawRect(x,y,x+w*Math.max(0,q),y+h,p);}boolean in(float x,float y,float l,float t,float rr,float b){return x>=l&&x<=rr&&y>=t&&y<=b;}float dist(float a,float b,float c,float d){return (float)Math.hypot(a-c,b-d);}int color(int i){int[] a={0xffffc04d,0xff5bd69d,0xffb4875d,0xffffdf55,0xffc970d8,0xffef765b,0xff7bdcf4,0xffff8b35};return a[i];}
  static class U{int team,type;float x,y,lane,hp,max,dmg,sp,range,rate,cd,rad;boolean build;void set(float h,float d,float s,float g,float r,float z,boolean b){hp=max=h;dmg=d;sp=s;range=g;rate=r;rad=z;build=b;}}
  static class T{int team;float x,y,hp,max,range,cd;boolean core,ok=true;T(int a,float b,float c,boolean d){team=a;x=b;y=c;core=d;max=hp=d?3300:2100;range=d?330:300;}}
}
